dataset: mnist #options [cifar, mnist, fashion-mnist]
backbone: 18 #options [18, 34, 50, 101, 152]
pretrained: True # ignore for now
normal_class_indx: 0
batch_size: 32
auc_every: 1 # Takes too much time
n_epochs: 10 # Number of all iterations

train_attack:
  attack_type: PGD
  attack_params: { "eps": 0.03, "steps": 10 }

knn_attack: False # TODO, keep it false
results_path: ./results/ # saves results as csv row in this folder
output_file_name: train_results # saves csv file with name {ou   tput_file_name}.csv
use_gan: True # if True, uses Gan images as exposure
exposure_folder: "./CURRENT-CLASS-EXPOSURE/" # Path to the folder of .png files
bw: True # Black & White
eps: 8 # the noise magnitude gonna be eps/255
earlystop_attack: True
